### ISSUE TITLE
Muted players can still chat

### ISSUE THREAD

**Issue by Kiro47** [Chosencraft/ChosenChat#13]
Since we use essentials to handle chats we'll want to be able to hook into their API.
You should be able to do this via one of two ways, either directly through the essentialsX API or via the Vault API which essentials hooks into.
``IEssentials ess = (IEssentials) Bukkit.getPluginManager().getPlugin("Essentials");``
essentialsx : https://www.spigotmc.org/resources/essentialsx.9089/
possibly helpful forum thread: https://www.spigotmc.org/threads/essentialsx-api-checking-if-a-player-is-afk.245504/

For Vault 
https://dev.bukkit.org/projects/vault
They provide their own documentation for handling their API.

Essentially you need to check if the player is muted when they attempt to chat, and if they are, you'll want to cancel the event and send them back a message saying they are muted.

**Comment by theNewton17** [comment]
done, although essentials or vault seems to already have a message for reminding players they are muted so I didn't add that.
