### ISSUE TITLE
Add support for chat formatting

### ISSUE THREAD

**Issue by Kiro47** [Chosencraft/ChosenChat#2]
We want to be able to use formatted chat in our messages and to do it with the '&' character.  We also want to follow this formatting chart: https://minecraft.gamepedia.com/Formatting_codes .
We want 3 types of permission nodes for this at a minimum: one for colours, formatting, and obfuscated text.  If those permissions also have sub permissions for each colour and format type that would also be nice.

**Comment by theNewton17** [comment]
Colors and formatting is implemented, still working on permissions mostly because that's tied to ranks and I'm doing that all at once.
