### ISSUE TITLE
Invalid color should not change the current colorr

### ISSUE THREAD

**Issue by Kiro47** [Chosencraft/ChosenChat#5]
Currently if you use an invalid colour using /channel set <colour> <colourname> and the colour name is not on the list it default to white, this should be considered unintended behaviour as it is a bad design choice.  If a colour value is invalid, is should default to changing nothing and just returning that X is an invalid colour name.

**Comment by theNewton17** [comment]
fixed, won't find it in the commit messages but it was part of fixing color names to default values
