### ISSUE TITLE
Changing <channel name> to [channel name]

### ISSUE THREAD

**Issue by Kiro47** [Chosencraft/ChosenChat#6]
The command 
/channel set <channel name> <setting> <value>
should be
/channel set [channel name] <setting> <value>

This is due to channel name being optional and it defaulting to your current channel if not specified.
Standard convention denotes brackets as optional parameters and arrows as mandatory parameters.
More details found at: https://support.code42.com/Administrator/Cloud/Administration_console_reference/Administration_console_command-line_interface_reference

**Comment by theNewton17** [comment]
just so I don't forget: currently the channel name isn't used at all; the command executes for your current channel and you cannot specify a different channel. I plan on changing this but I've forgotten it once already.

**Comment by theNewton17** [comment]
added support for [channel name] to be the first arg, so the command
/channel Trade set color gold
sets the color of the Trade Channel to gold

keeping the issue open until I fix a bug where /channel adskrhjutggf (a nonexistent channel) causes nullPointers

**Comment by theNewton17** [comment]
fixed nullpointers when trying to refer to a nonexistent channel
