### ISSUE TITLE
Channels being deleted on being being empty

### ISSUE THREAD

**Issue by Kiro47** [Chosencraft/ChosenChat#8]
Currently when a channel becomes empty, sometimes the channel will automatically delete itself.  This could be a problem when people leave for a few minutes to talk in another channel.  This behaviour should be limited to on channel deletion manually and on server restarts.

**Comment by theNewton17** [comment]
This was intended behavior but I can change it. currently a channel that is not set to permanent gets deleted if it is empty.

**Comment by Kiro47** [comment]
Probably best to do as said above, otherwise we'll have a ton of complains about channels automatically being deleted.

**Comment by theNewton17** [comment]
Channels now only get deleted when the plugin gets reloaded, a side effect of this is that now when the server restarts, all players join General chat, and the same happens when a single player logs off.
